spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

finvista.seed.enabled=true
finvista.admin.nome=${FINVISTA_ADMIN_NOME:}
finvista.admin.email=${FINVISTA_ADMIN_EMAIL:}
finvista.admin.senha=${FINVISTA_ADMIN_SENHA:}

finvista.cliente.nome=${FINVISTA_CLIENTE_NOME:}
finvista.cliente.email=${FINVISTA_CLIENTE_EMAIL:}
finvista.cliente.senha=${FINVISTA_CLIENTE_SENHA:}

# Sessao HTTP em producao
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true